### ISSUE TITLE
Possibly replace required-labels?

### ISSUE THREAD

**Issue by mathomp4** [yogevbd/enforce-label-action#6]
A query for the dev. Do you think this action could (eventually) replace my reliance on https://github.com/dimagi/required-labels If there's a way to use Github Actions instead of Heroku, it sounds like a good thing to me.

But, am I right in my reading that this doesn't yet have all the same functionality?

**Comment by yogevbd** [comment]
It does have the same functionality now 😊.
You can easily move to Github Actions by adding the yml file as described in the [Readme file](https://github.com/yogevbd/enforce-label-action/blob/master/README.md).
Let me know if you encounter issues or missing functionality. Thanks!

**Comment by mathomp4** [comment]
@yogevbd Ooh. Nice. Thanks. I'll try it out. There might be some more thoughts coming maybe based on this: https://github.com/dimagi/required-labels/issues/28 (i.e., some way to tell people they should add a label x, y, z...)

But until then, I think I'm stupid/newbie. I'm trying it out here but it doesn't seem to mind I don't have any labels: https://github.com/mathomp4/labeltest-github-actions/pull/2

**Comment by yogevbd** [comment]
The readme file was misleading.. sorry for the inconvenience.
Created a pull request in https://github.com/mathomp4/labeltest-github-actions/pull/3 with the fix.
And it's defiantly possible and easy to add description labels.. will add it soon.

**Comment by yogevbd** [comment]
Added check run failure description support. See the updated [Readme file](https://github.com/yogevbd/enforce-label-action/blob/master/README.md).

**Comment by mathomp4** [comment]
@yogevbd Sorry for being out of touch on this. Work has been...worky. But I'm back on it. I tried updating my `.github/workflows/enforce-labels.yml` but I seem to have broken something. When I made a test PR at https://github.com/mathomp4/labeltest-github-actions/pull/4 it's happy with no labels at all.

Any ideas what I might have done wrong?

**Comment by yogevbd** [comment]
The syntax was wrong. I suggested a fix in https://github.com/mathomp4/labeltest-github-actions/pull/5

**Comment by mathomp4** [comment]
Well I feel stupid. I kept staring at the complex stuff below.

It does work! I wish there was a good way to see the "You need different flags" text on the PR page rather than having to drill down into the Actions tab. Not sure why github can't just make that bit of the "Review required" box bigger! or expandable.

But, if do go to the [Checks tab](https://github.com/mathomp4/labeltest-github-actions/pull/4/checks?check_run_id=694292866) I do see in the run step:
```
##[error]Select at least one label ['bug','enhancement','wontfix']
##[error]Select at least one label ['required']
```
Woot!

(Though, I've always wondered how GitGuardian gets that [nice pretty page](https://github.com/mathomp4/labeltest-github-actions/pull/4/checks?check_run_id=694292584). My guess: money 😄 )

**Comment by mathomp4** [comment]
As I try to clean up, I can definitely say @yogevbd helped me out with this. I will close.

Though fair warning to @yogevbd, I am looking at label actions again... 😄
